# Generated by Django 4.0.4 on 2022-04-23 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=55)),
                ('adress', models.CharField(max_length=55)),
                ('phone_nuadressmber', models.CharField(max_length=55)),
                ('index', models.CharField(max_length=55)),
                ('pin', models.IntegerField()),
                ('first_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
